### ISSUE TITLE
Notice error for tracking resi in telegram

### ISSUE THREAD

**Issue by litanur** [luridarmawan/SimpleAI#28]
**Me:** tolong cek resi jne 1234567890

Carik:
<div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">
<h4>A PHP Error was encountered</h4>
<p>Severity: Notice</p>
<p>Message:  Undefined index: cnote</p>
<p>Filename: controllers/jnews.php</p>
<p>Line Number: 712</p>
</div><div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">
<h4>A PHP Error was encountered</h4>
<p>Severity: Notice</p>
<p>Message:  Undefined index: cnote</p>
<p>Filename: controllers/jnews.php</p>
<p>Line Number: 716</p>
</div><div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">
<h4>A PHP Error was encountered</h4>
<p>Severity: Notice</p>
<p>Message:  Undefined index: cnote</p>
<p>Filename: controllers/jnews.php</p>
<p>Line Number: 717</p>
</div><div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">
<h4>A PHP Error was encountered</h4>
<p>Severity: Notice</p>
<p>Message:  Undefined index: cnote</p>
<p>Filename: controllers/jnews.php</p>
<p>Line Number: 723</p>
</div><div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">
<h4>A PHP Error was encountered</h4>
<p>Severity: Notice</p>
<p>Message:  Undefined index: cnote</p>
<p>Filename: controllers/jnews.php</p>
<p>Line Number: 744</p>
</div><div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">
<h4>A PHP Error was encountered</h4>
<p>Severity: Notice</p>
<p>Message:  Undefined index: cnote</p>
<p>Filename: controllers/jnews.php</p>
<p>Line Number: 765</p>
</div>{"rajaongkir":{"query":{"waybill":"1234567890","courier":"jne"},"status":{"code":200,"description":"OK"},"result":{"delivered":false,"summary":{"couriercode":"jne","couriername":"Jalur Nugraha Ekakurir (JNE)","waybillnumber":null,"servicecode":null,"waybilldate":"2012-07-27","shippername":"COUNTER PM NOOR","receivername":"LILA","origin":"SAMARINDA","destination":"JAKARTA","status":null},"details":{"waybillnumber":"1234567890","waybilldate":"2012-07-27","waybilltime":"10:24","weight":".1","origin":"SAMARINDA","destination":"JAKARTA","shipppername":"COUNTER PM NOOR","shipperaddress1":"ALI","shipperaddress2":"JL PM NOOR NO.1","shipperaddress3":"","shippercity":"SAMARINDA","receivername":"LILA","receiveraddress1":"JL SURABAYA TJ PRIOK","receiveraddress2":"",

**Comment by luridarmawan** [comment]
this error was produced by third-party.
